version: 2
jobs:
  build:
    
    working_directory: ~/estolowka

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout
      - run: ls
      - restore_cache:
          key: estolowka-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: estolowka-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      