version: 2
jobs:
  test_backend:
    
    working_directory: ~/estolowka/estolowka-backend

    docker:
      - image: circleci/openjdk:8u171-jdk

    steps:
      - checkout:
          path: ~/estolowka
      - restore_cache:
          key: estolowka-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: estolowka-{{ checksum "pom.xml" }}
      - run: mvn test

  test_frontend:
    working_directory: ~/estolowka/estolowka-frontend
    docker:
      - image: circleci/node:10.15.3-browsers-legacy
    steps:
    - checkout:
        path: ~/estolowka
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run:
        name: Install local dependencies
        command: npm install
    - save_cache:
        key: v1-dependencies-{{ checksum "package.json" }}
        paths:
        - node_modules
    - run:
        name: Testing
        command: npm run test -- --no-watch --no-progress
  deployment:
    working_directory: ~/estolowka
    docker:
    - image: circleci/openjdk:8u171-jdk
    environment:
      DOCKER_TLS_VERIFY: "1"
      DOCKER_HOST: "tcp://142.93.77.76:2376"
      DOCKER_CERT_PATH: "certs"
    steps:
    - run:
        name: Install Docker Compose
        command: |
          curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
          chmod +x ~/docker-compose
          sudo mv ~/docker-compose /usr/local/bin/docker-compose
    - setup_remote_docker
    - run:
        name: Create dir and certs file
        command: |
          mkdir -p $DOCKER_CERT_PATH
          echo "$CA" > $DOCKER_CERT_PATH/ca.pem
          echo "$CLIENT_CERT" > $DOCKER_CERT_PATH/cert.pem
          echo "$CLIENT_KEY" > $DOCKER_CERT_PATH/key.pem
    - run:
        name: Check docker-compose works
        command: docker-compose version
    -run:
        name: Remove cert dir
        command: rm -rf $DOCKER_CERT_PATH
workflows:
  version: 2
  test_app_deploy:
      - deployment