version: 2
jobs:
  build:
    
    working_directory: ~/estolowka/estolowka-backend

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout:
          path: ~/estolowka
      - restore_cache:
          key: estolowka-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: estolowka-{{ checksum "pom.xml" }}
          
      - run: mvn test
      